# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use Node.js 18 for compatibility with the application requirements
FROM node:18-alpine AS builder

# Create and set the working directory
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package.json package-lock.json ./

# Install the project dependencies
RUN npm install

# Copy the rest of the project files
COPY . .

# Build the TypeScript files
RUN npm run build

# Use a minimal Node.js image for the production environment
FROM node:18-alpine AS release

# Set the working directory
WORKDIR /app

# Copy the built files and node_modules from the builder stage
COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/node_modules /app/node_modules
COPY --from=builder /app/package.json /app/package.json

# Set environment variables
ENV NODE_ENV=production

# Start the server
ENTRYPOINT ["node", "dist/index.js"]